// Generated by CoffeeScript 1.12.4
(function() {
  var browserSync, coffee, gulp, jshint, path, php, reload, sass, sourcemaps;

  gulp = require('gulp');

  jshint = require('gulp-jshint');

  sass = require('gulp-sass');

  browserSync = require('browser-sync');

  reload = browserSync.reload;

  sourcemaps = require('gulp-sourcemaps');

  coffee = require('gulp-coffee');

  php = require('gulp-connect-php');

  path = 'wp-content/themes/fotogaleria/';

  gulp.task('jshint', function() {
    return gulp.src(path + 'js/**/*.js').pipe(jshint()).pipe(jshint.reporter('default'));
  });

  gulp.task('browser-sync', function() {
    browserSync.init({
      proxy: '127.0.0.1',
      port: 8080,
      open: false
    });
    return gulp.watch([path + '*.php', path + 'style.css', path + 'js/app.js'], reload);
  });

  gulp.task('sass', function() {
    return gulp.src(path + 'sass/style.sass').pipe(sourcemaps.init()).pipe(sass({
      errLogToConsole: true,
      outputStyle: 'compressed'
    })).pipe(sourcemaps.write()).pipe(gulp.dest(path));
  });

  gulp.task('coffee', function() {
    return gulp.src(path + 'coffee/app.coffee').pipe(sourcemaps.init()).pipe(coffee({
      bare: true
    })).pipe(sourcemaps.write()).pipe(gulp.dest(path + 'js'));
  });

  gulp.task('php', function() {
    return php.server({
      base: '.',
      port: 8010,
      keepalive: true
    });
  });

  gulp.task('watch', function() {
    gulp.watch(path + 'sass/**/*.sass', ['sass']);
    gulp.watch(path + 'js/**/*.js', ['jshint']);
    gulp.watch(path + 'coffee/**/*.coffee', ['coffee']);
    return gulp.watch(path + '*.php', ['php']);
  });

  gulp.task('default', ['jshint', 'watch', 'browser-sync']);

}).call(this);
